name: Portfolio Deploy

on:
  workflow_dispatch:
  push:
      branches:
        - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check repo
        uses: actions/checkout@v4
      
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist